import {
  Anchor,
  Beer,
  Book,
  BookOpen,
  Castle,
  Church,
  Clapperboard,
  Coffee,
  Croissant,
  Crown,
  Drama,
  Dumbbell,
  Flame,
  Flower2,
  Footprints,
  Frame,
  IceCreamCone,
  Landmark,
  MapPin,
  Mountain,
  Music,
  Sandwich,
  ShoppingBasket,
  Sparkles,
  Star,
  Store,
  Sunset,
  TrainFront,
  Trees,
  Umbrella,
  UtensilsCrossed,
  Wine,
  type LucideIcon,
} from 'lucide-react'
import type { LevelKey } from '../lib/levels'

const CATEGORY_ICONS: Record<string, LucideIcon> = {
  cafe: Coffee,
  restaurant: UtensilsCrossed,
  fast_food: Sandwich,
  food_court: UtensilsCrossed,
  bar: Wine,
  pub: Beer,
  biergarten: Beer,
  bakery: Croissant,
  pastry: Croissant,
  ice_cream: IceCreamCone,
  park: Trees,
  nature_reserve: Trees,
  wood: Trees,
  garden: Flower2,
  beach: Umbrella,
  peak: Mountain,
  museum: Landmark,
  gallery: Frame,
  arts_centre: Frame,
  library: BookOpen,
  books: Book,
  viewpoint: Sunset,
  pier: Anchor,
  marina: Anchor,
  attraction: Sparkles,
  theme_park: Sparkles,
  castle: Castle,
  place_of_worship: Church,
  supermarket: ShoppingBasket,
  convenience: Store,
  marketplace: Store,
  cinema: Clapperboard,
  theatre: Drama,
  music_venue: Music,
  nightclub: Music,
  fitness_centre: Dumbbell,
  station: TrainFront,
  tram_stop: TrainFront,
  platform: TrainFront,
}

export function categoryIcon(category?: string): LucideIcon {
  return (category && CATEGORY_ICONS[category]) || MapPin
}

export const LEVEL_ICONS: Record<LevelKey, LucideIcon> = {
  saved: MapPin,
  visited: Footprints,
  favourite: Star,
  regular: Flame,
  legend: Crown,
}
